TOML DOES NOT SUPPORT COMMENTS
DELETE THESE INSTRUCTIONS BEFORE DEPLOYING
SET YOUR TELEGRAM BOT TOKEN WITH TELEGRAM_BOT_TOKEN BELOW
RENAME THIS FILE TO Secrets.toml
DELETE THESE INSTRUCTIONS BEFORE DEPLOYING
DELETE THIS AND EVERYTHING ABOVE IT

TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
